#Dockerfile.dev

FROM node:20-alpine

WORKDIR /app

# dependencies install for dev server
COPY package.json package-lock.json* yarn.lock* pnpm-lock.yaml* ./

RUN npm install

# Copy project
COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]
