version: "3.9"

services:
  db:
    image: postgres:16
    container_name: embassy_db
    environment:
      POSTGRES_DB: embassy
      POSTGRES_USER: embassy
      POSTGRES_PASSWORD: Markhoyor4312@
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile         # ← Чиний байгаа Dockerfile
    container_name: embassy_backend
    working_dir: /app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1
      - DB_PASSWORD=embassy_password_change_me
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev     # ← Чиний хэлснээр энд .dev байгаа
    container_name: embassy_frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3100:3000"
    environment:
      - WATCHPACK_POLLING=true
      - API_INTERNAL_BASE_URL=http://backend:8000
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NEXT_PUBLIC_MEDIA_BASE_URL=http://localhost:8000
    depends_on:
      - backend

volumes:
  postgres_data:
