# Generated by Django 5.2.8 on 2025-11-14 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=320, unique=True)),
                ('language', models.CharField(choices=[('mn', 'Mongolian'), ('en', 'English'), ('id', 'Indonesian')], default='mn', max_length=2)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('body', models.TextField()),
                ('published_at', models.DateTimeField()),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=200)),
                ('language', models.CharField(choices=[('mn', 'Mongolian'), ('en', 'English'), ('id', 'Indonesian')], default='mn', max_length=2)),
                ('title', models.CharField(max_length=300)),
                ('body', models.TextField()),
            ],
            options={
                'unique_together': {('slug', 'language')},
            },
        ),
    ]
