# Generated by Django 5.2.8 on 2025-11-14 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='pages/heroes/'),
        ),
    ]
