# Generated by Django 5.2.8 on 2026-03-13 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    # CODEX: Dynamic navbar-д зориулсан MenuItem model-ийн schema migration.

    dependencies = [
        ('core', '0004_newsimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.CharField(choices=[('mn', 'Mongolian'), ('en', 'English'), ('id', 'Indonesian')], default='mn', max_length=2)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('item_type', models.CharField(choices=[('internal_page', 'Internal page'), ('internal_path', 'Internal path'), ('external_url', 'External URL')], default='internal_path', max_length=20)),
                ('path', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField(blank=True)),
                ('open_in_new_tab', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_items', to='core.page')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.menuitem')),
            ],
            options={
                'ordering': ['language', 'parent_id', 'order', 'id'],
            },
        ),
    ]
